# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /res/favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

#page setting - disquz comment
enabled_disqus : false
disqus_url : 'https://morgan-hexo-theme.disqus.com/embed.js'

#page setting - slogan
slogan : [ "心事浩渺连广宇，于无声处听惊雷", "高山仰止，景行行止，虽不能至，然心向往之", "这里是 SDYZMUN 的官方博客" ]
slogan_random_display : false
slogan_color: "#404040"

#page setting - blog title color
title_color : "#404040"
title_background_color :  "#f7f7f7"

#page setting - menu color
menu_text_color : "#5a5a5a"
menu_background_color : "#f7f7f7"

#page setting - article color
article_color : "#3498db" 
article_color_hover : "#34b2db" 
article_color_active : "#2075c1" #rgb(0, 188, 255)"

#page feature - about me
enabled_about_me : true
about_me : "关于 SDYZMUN"
about_me_content : "立志于成为邵阳市乃至湖南省超一流的模拟联合国平台与学生社团，成立于 2015 年的邵东一中模拟联合国（SDYZMUN）由学生管理，以热情驱动。秉持「学术为先」的理念，发展中的 SDYZMUN 已然成为邵东一中社团系统中不可或缺的一部分，并在湖南省发挥着难以忽视的作用。尽管发展时间不长，我们的足迹已遍布全国乃至全球各地。从市会到省会，从环梦到北大，一中模联人都曾焕发过光彩，而我们的征途，是星辰大海。"

#footer content
footer_big_content : "SDYZMUN, 2019"
footer_small_content : "使用 CC BY-NC-SA 3.0 许可"

#github setting
theme: jekyll-theme-cayman
